name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "**"
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Frontend to S3 + CloudFront
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build frontend (static export)
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync static site to S3
        run: |
          S3_BUCKET="spot-the-pie-39472434234"
          aws s3 sync ./dist s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@ == 'spot-the-pie.schleo.com']].Id" --output text)
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"
